src/components/Button.vue, src/demos/Buttons.vue
- updating the is and type props
- cleaned up focus and hover states
- added click event info to doc table
=> button docs update and switched a prop to it makes more sense

src/components/LeftNavigation.vue, src/components/ProgressBar.vue, src/demos/ProgressBars.vue, src/views/Documentation.vue
=> Progress bar only again

src/components/LeftNavigation.vue, src/components/ProgressBar.vue, src/demos/ProgressBars.vue, src/views/Documentation.vue
- eds progress bar plus small doc change
=> Progress bar testing

src/components/ImagePicker.vue, src/demos/ImagePickers.vue, src/demos/LeftNavigation.vue, src/styles/imports/Mixins.less, src/system.js, src/views/Documentation.vue
Base for image picker, 
file data might be sent through $emit , I'm not sure if that part works.
for your perusal.
=> Image Picker Base

src/components/Spinner.vue, src/demos/Spinners.vue
added more documentation,
fixed some typos
=> Spinner doc

src/components/SSProSimulator.vue
- added transitions between different themes
- for loop to restart when it ends, doesnt stop at `lime`
=> Pro simulator

src/demos/Banners.vue
=> Fix props description

sl-email-template.html, sl-email.html, src/components/Accordion.vue, src/components/Badge.vue, src/components/Button.vue, src/components/NewFeatureOverlay.vue, src/components/TabDevelop.vue, src/components/Tabs.vue, src/components/VirtualItem.vue, src/demos/Announcements.vue, src/demos/Banners.vue, src/demos/Tabs.vue
・added video
・mp4 or webm files are acceptable now
・responsible 
・done documentation
=> New feature fix

src/components/Button.vue, src/demos/Badges.vue, src/demos/Buttons.vue
・added paypal for platform option
=> Add paypal color for stylesheet

package-lock.json, package.json, src/components/CallToAction.vue, src/demos/CallToActions.vue, yarn.lock
added props for Button component so we can use it as a tag or router-link
=> Calltoaction

package-lock.json, package.json, src/components/CallToAction.vue, src/components/ContentRow.vue, src/demos/CallToActions.vue, src/demos/Layouts.vue, yarn.lock
=> Contentrow

package-lock.json, package.json, src/components/Badge.vue, src/components/CallToAction.vue, src/components/ContentRow.vue, src/components/NewFeatureOverlay.vue, src/demos/Badges.vue, src/demos/CallToActions.vue, src/demos/Layouts.vue, yarn.lock
responsive design was not proper. breakpoint and stylesheet are fixed.
=> New feature overlay

src/components/CallToAction.vue, src/demos/CallToActions.vue
added props for thumbnail background color
=> Add thumbnailBg

src/components/EmptySection.vue
- set title color of empty section
=> set title color of empty section

src/components/Button.vue, src/components/ModalBasic.vue, src/components/ModalComp.vue, src/components/ModalConfirmation.vue, src/components/ModalRedirect.vue, src/components/ModalSubscribe.vue, src/components/NewFeatureOverlay.vue, src/components/Selector.vue, src/components/TabDevelop.vue, src/demos/Inputs.vue, src/styles/imports/Colors.less
- added documentation and styling for multi select and disabled
- reis modal updates
=> Multiselect

src/components/CallToAction.vue, src/demos/CallToActions.vue
- when we want to use both click and a link, It should not do preventDefault. 
- I use it for obs-widget pages.
=> Change click method of button

src/App.vue, src/demos/LeftNavigation.vue, src/demos/index.ts, src/router.ts, src/views/Documentation.vue
this will dynamically grab all the demo components out of the demos folder and generate routes and left nav items for them 🙌
=> this should make the nav work well, all the demos are dynamic

src/components/Onboarding.vue, src/components/OnboardingStep.vue, src/demos/Onboardings.vue
- changed logic for steps prop
- added onComplete
=> Onboarding

src/components/Checkbox.vue, src/demos/Inputs.vue
- attribute name and value are set in streamlabs.com so need to add those to Checkbox component
=> Add attribute to checkbox

src/components/SiteSearch.vue
=> nested all css

src/components/Checkbox.vue, src/demos/Inputs.vue
- added 'label for' to letting label clickable. this part was somehow managed by method before
- added `checked` attribute, `isChecked` prop
- deleted method to change value every time we click. each value should not be changed
=> Fix checkbox

src/components/Slider.vue, src/demos/Sliders.vue
=> Add disabled prop

package.json, src/components/SiteSearch.vue, yarn.lock
Removed vue-fuse, as its not needed anymore,
-This also changed the need to have an old version of vue through the resolutions.
=> changed highlight reset & removed vuefuse dependency

src/components/Tabs.vue
- Added missing .night wrapper for SL.com so tabs can be used properly there 😸
=> Night Theme Fix for Tabs

src/components/Accordion.vue, src/demos/Accordions.vue, src/demos/Callouts.vue, src/demos/VirtualItems.vue
also fixed up some documentation for it
=> update for left-nav

src/components/Radio.vue
=> onClick event fix

src/components/Accordion.vue
- Use slot if the slot has data, otherwise use accordionTitle
=> Accordion Fix

src/App.vue, src/components/Toggle.vue, src/demos/Toggles.vue
- Made Toggle v-model compatible for ease of use
- Updated demos to use v-model
- Toggle updated in app.vue to fit new values
- Updated demo code snippets
=> Toggle Tweaks

src/components/Accordion.vue, src/system.js
=> Accordion title width 100%

src/components/Guard.vue, src/demos/Guards.vue, src/styles/imports/Colors.less
- Adjusted guard css to use s- prefix
=> s- prefix guard instead of beaker-

index.d.ts, package.json, src/components/DatePicker.vue, src/components/Guard.vue, src/components/PaneDropdown.vue, src/demos/Calendars.vue, src/demos/Sliders.vue, src/system.js, yarn.lock
- Created Date Picker based on [vuejs-datepicker](https://www.npmjs.com/package/vuejs-datepicker) component.
- Wrapped Date Picker in Pane Dropdown component.
- Added Prop `autoHeight` to Pane Dropdown component to remove 300px height limit.
=> Date picker

src/components/DatePicker.vue, src/demos/Calendars.vue
- Add variant prop with toggle style option.
- Updated `Calendars` page with updated prop info and demo.
=> Add toggle variant

src/components/Toggle.vue
- Changed font weight of unselected toggle options to match design system.
=> Fix toggle text variant style to match design system

src/components/Badge.vue, src/components/Button.vue, src/components/EmptySection.vue, src/components/PrimeSection.vue, src/demos/Badges.vue, src/demos/Prime.vue, src/router.ts, src/styles/imports/Colors.less
- prime section component and 2 prime badge variations
=> Prime component

package.json, src/components/DatePicker.vue, src/system.js, yarn.lock
- removing vuejs-datepicker for now
- moved vue to peerdep
- removed 2 unused packages
=> Testing dep

src/components/Guard.vue
=> Fixed Guard Alt variation

azure-pipelines.yml
For now, this will just compile the assets and run the linter.  When we have tests, this can run tests as well.
=> Set up azure pipelines CI

src/components/CSLayoutPicker.vue, src/components/VirtualItem.vue
should fix the layout bug we're getting in slobs when trying to add a new row to creator site
=> Layout picker fix

src/components/SliderTwo.vue, src/demos/Sliders.vue, src/system.js
New slider, 
Currently it is slider-two so that it doesn't interfere with current sliders.
=> New slider

package.json, src/components/ModalComp.vue, src/components/ModalSubscribe.vue
=> Modal upgrade

src/system.js
=> Export TaggingInput

src/components/SliderTwo.vue, src/demos/Sliders.vue
-possible fix for custom data,
-fix to css if properly nested.
-error message added for improper use of steps/interval
=> New slider 05

package.json, src/components/Button.vue, src/components/ModalSubscribe.vue
- Add paypal icon to `paypal-blue` variation.
- Increase top padding on bottom notes section.
=> Subscribe modal

src/components/SliderTwo.vue, src/components/TaggingInput.vue, src/components/TextInput.vue, src/demos/Sliders.vue
=> possible fix for sluggish response in slobs

src/components/TaggingInput.vue
- remove defaults for label & placeholder
=> remove defaults for label & placeholder

src/components/TextInput.vue, src/demos/Inputs.vue
- Added a basic Spinner & Scroll behaviour when type is number for TextInput
=> TextInput Number support

src/components/SliderTwo.vue, src/demos/Sliders.vue
Still Testing, Will clean code before it goes in for real.
=> fixed overshoot, fixed custom data

src/components/TextInput.vue, src/demos/Inputs.vue
- Fixed Arrow Position
- Added Step, Min & Max props to TextInput for Number control
- Fixed Colors & Font Awesome Icon
=> Number Fixes

src/components/TextArea.vue, src/components/TextInput.vue, src/demos/Inputs.vue, src/styles/components/Inputs.less, src/styles/imports/Mixins.less, src/system.js
- Added TextArea
* autoReize
* v-model
* rows
* cols
* maxLength
* maxHeight
* label
* placeholder
- Fixed TextInput issues on SL.com
=>  New TextArea & TextInput Fixes

src/components/ModalBasic.vue, src/components/ModalComp.vue, src/components/ModalConfirmation.vue, src/components/ModalRedirect.vue, src/components/ModalSubscribe.vue, src/components/SliderTwo.vue, src/components/TextInput.vue, src/demos/Inputs.vue
- Add `v-on="$listeners"` to modals.
- Ran lint
=> Allow beaker modals to use vue modal js events

src/components/TextArea.vue
- Text Area rows used
- Resize vertically only
=> Text Area Fixes

src/components/TextArea.vue, src/components/TextInput.vue
- Added focus function to Text Area & Text Input
=> Added Focus Function

src/components/TextInput.vue, src/demos/Inputs.vue, src/styles/components/Inputs.less
- Added autocomplete prop (off by default)
- Added css to get rid of white background & black text on autofill / complete behavior
=> Auto Complete TextInput behavior

src/components/BannerDiscord.vue
- Pass Discord Banner button click event to parent
=> Banner discord fix

src/components/ModalBasic.vue
=> Emit confirm on Modal Basic

src/components/Onboarding.vue, src/demos/Onboardings.vue
Updated Onboarding Component to allow for named steps.
Updated Documentation to reflect this.
=> Onboarding named

src/components/ModalBasic.vue
- Optional divs so when not used the padding doesn't stack.
=> Optional divs

README.md, build-deploy-gh-pages.sh, package.json
this will allow us to deploy our beaker docs again
=> fixing beaker docs

src/components/Button.vue
- added font-awesome for icon prop
=> Add font-awesome for icon

src/components/Loading.vue, src/demos/Loaders.vue
Added a Prop to allow the component to be used without fixed positioning, useful for slobs.
=> Loading nofixed

src/components/SliderTwo.vue
Testing slidertwo in slobs again .
=> fix for tiny slidertwo in slobs

src/components/Onboarding.vue
I'll admit this is somewhat sloppy but I'm trying to add needed reactivity functionality without breaking existing things. Ideally current and currentSteps should not be separate properties
=> Add reactivity to onboarding

src/components/Button.vue, src/components/CallToAction.vue, src/demos/CallToActions.vue
- add props for prime background image
=> Add bgPrime for CallToAction

src/components/TextArea.vue
- Added missing input to v-model updates when auto completed
=> Added missing input to v-model updates when auto completed

src/components/Badge.vue, src/components/Button.vue, src/demos/Buttons.vue, src/styles/imports/Typography.less
- update prime buttons with new design
- add simple prime button 
- update prime badge with new design
=> Update prime button and prime badge

src/components/Badge.vue, src/components/Button.vue, src/components/CallToAction.vue, src/components/StatusSwitch.vue, src/demos/Buttons.vue, src/demos/Inputs.vue
- Add size prop [string] to status switch. (For now only "small" option available)
- Add more transitions
- Ran linter
=> Change style size from em to pixel to match beaker mocks

src/demos/Inputs.vue
- update documentation about status switch because import and component
names are not correct and make team members confused
=> docs(status-switch): update documentation

src/components/Button.vue, src/demos/Buttons.vue
- add 2 props named slobsDownloadTitle and osType in case we need to
update theme
- add slot for the bottom text
- hover action is applied
- background color is changed in the night mode
=> feat(button): add new slobs download button

src/components/Button.vue, src/components/PaneDropdown.vue, src/demos/Buttons.vue
- fix(panedropdown): change v-if to v-show and run lint
=> Change PaneDropdown reveal from v-if to v-show for SEO

src/components/ModalBasic.vue, src/components/ModalComp.vue, src/demos/Modals.vue
adding this prop from vue-js-modal plugin
[![Screenshot from Gyazo](https://gyazo.com/604e72d10a2ab8aff152d33a45383fd0/raw)](https://gyazo.com/604e72d10a2ab8aff152d33a45383fd0)
=> chore(modal): add clickToClose prop to ModalBasic

src/components/SiteSearch.vue
Adds background to unfocused state in Site Search component.
https://gyazo.com/8d9385486ab17c4f623f5d39b3d5e78c
=> Update Site Search bg color

src/components/Checkbox.vue, src/components/Radio.vue, src/components/StatusSwitch.vue
[![Image from Gyazo](https://i.gyazo.com/8f91d032fbf7726a6f95590a88c4379b.png)](https://gyazo.com/8f91d032fbf7726a6f95590a88c4379b)
[![Image from Gyazo](https://i.gyazo.com/ca562ccfc275fa0c5da3229a2d01bf16.png)](https://gyazo.com/ca562ccfc275fa0c5da3229a2d01bf16)
[![Image from Gyazo](https://i.gyazo.com/65855c5f03615f99c77d9b7e86fca303.png)](https://gyazo.com/65855c5f03615f99c77d9b7e86fca303)
=> chore: color update to match the beaker color

src/components/PrimeIntro.vue
Updating text for prime features
=> chore: update text

src/components/Selector.vue
add a slot for this empty list message:
=> add noResult slot to selector

src/styles/imports/Colors.less
=> Update discord color

package.json, tsconfig.json
Reverts stream-labs/beaker#560
=> Revert "update tsconfig.json to support webpack"
